# Generated by Django 2.0.6 on 2018-07-13 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0002_inviter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=80, null=True)),
                ('first_name', models.CharField(max_length=80, null=True)),
                ('age', models.PositiveSmallIntegerField(null=True)),
                ('email', models.CharField(max_length=80, null=True)),
                ('password', models.CharField(max_length=80, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='inviter',
            name='event',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='adresse',
            new_name='addresse',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='auteur',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='titre',
            new_name='title',
        ),
        migrations.DeleteModel(
            name='Inviter',
        ),
        migrations.AddField(
            model_name='guest',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event'),
        ),
        migrations.AddField(
            model_name='guest',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
