# Generated by Django 2.0.6 on 2018-07-16 07:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0004_auto_20180713_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('core', models.CharField(max_length=512)),
                ('like', models.PositiveSmallIntegerField(default=0)),
                ('dislike', models.PositiveSmallIntegerField(default=0)),
                ('edited', models.DateTimeField(null=True, verbose_name='date edited')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('response_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Comment')),
            ],
        ),
    ]
